public:
  host: '%app.public_host%'
  resource: ../../src/Controller/PublicApi/
  type: annotation

internal:
  host: '%app.private_host%'
  resource: ../../src/Controller/PrivateApi/
  type: annotation
