public:
  host: '%app.public_host%'
  prefix: /v1
  resource: ../../src/Controller/PublicApi/v1/
  type: annotation

private:
  host: '%app.private_host%'
  resource: ../../src/Controller/PrivateApi/
  type: annotation
