version: '3'

services:
  webapp:
    build: .
    volumes:
      - ../application:/var/www
      - ./xdebug.ini:/etc/php/7.2/mods-available/xdebug.ini
    env_file:
      - ../application/.env
    environment:
#       PhpStorm
      PHP_IDE_CONFIG: "serverName=grad_api"

  nginx:
    image: nginx:latest
    ports:
      - 8000:80
    volumes:
      - ../application:/var/www
      - ./nginx.conf:/etc/nginx/conf.d/default.conf

  mysql:
    ports:
      - 33060:3306
    image: mysql:5.7
    volumes:
      - mysql_data:/var/lib/mysql
    env_file:
      - ../application/.env

  redis:
    image: redis:4.0.11
    ports:
      - 63790:6379
    volumes:
      - redis_persistent:/data

volumes:
  mysql_data: {}
  redis_persistent: {}
