parameters:
    # Adds a fallback DATABASE_URL if the env var is not set.
    # This allows you to run cache:warmup even if your
    # environment variables are not available yet.
    # You should not need to change this value.
    env(DATABASE_URL): ''

doctrine:
    dbal:
        # configure these for your database server
        driver: '%env(DB_DRIVER)%'
        server_version: '%env(DB_SERVER_VERSION)%'
        charset: '%env(DB_CHARSET)%'
        default_table_options:
            charset: '%env(DB_CHARSET)%'
            collate: '%env(DB_COLLATION)%'
        mapping_types:
            enum: string
    #Урл из .env с переменными не переваривается в CLI, в итоге отваливаются действия с БД
        url: 'mysql://%env(DB_USER)%:%env(MYSQL_ROOT_PASSWORD)%@%env(DB_HOST)%:%env(DB_PORT)%/%env(MYSQL_DATABASE)%'
    orm:
        auto_generate_proxy_classes: false
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true
        mappings:
            App:
                is_bundle: false
                type: annotation
                dir: '%kernel.project_dir%/src/Entity'
                prefix: 'App\Entity'
                alias: App
