services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    Valkeru\PrivateApi\Auth\LoginRequest:
        factory:
        - '@App\Factory\ApiFactory'
        - 'makeApiRequest'
        arguments:
        - '@request_stack'
        - 'Valkeru\PrivateApi\Auth\LoginRequest'
