services:
  _defaults:
    autowire: true
    public: false
    autoconfigure: false

  Valkeru\PublicApi\Registration\RegistrationRequest:
    factory:
    - '@App\Factory\PublicApiFactory'
    - 'makePublicApiRequest'
    arguments:
    - '@request_stack'
    - '\Valkeru\PublicApi\Registration\RegistrationRequest'

  Valkeru\PublicApi\Auth\LoginRequest:
    factory:
    - '@App\Factory\PublicApiFactory'
    - 'makePublicApiRequest'
    arguments:
    - '@request_stack'
    - '\Valkeru\PublicApi\Auth\LoginRequest'

  Valkeru\PublicApi\Auth\LogoutRequest:
    factory:
    - '@App\Factory\PublicApiFactory'
    - 'makePublicApiRequest'
    arguments:
    - '@request_stack'
    - '\Valkeru\PublicApi\Auth\LogoutRequest'

  Valkeru\PublicApi\Security\TokenInfoRequest:
    factory:
    - '@App\Factory\PublicApiFactory'
    - 'makePublicApiRequest'
    arguments:
    - '@request_stack'
    - '\Valkeru\PublicApi\Security\TokenInfoRequest'
