services:
  _defaults:
    autowire: true
    public: false
    autoconfigure: false

  Valkeru\PublicApi\Registration\RegistrationRequest:
    factory:
    - '@App\Factory\PublicApiFactory'
    - 'makePublicApiRequest'
    arguments:
    - '@request_stack'
    - '\Valkeru\PublicApi\Registration\RegistrationRequest'

  Valkeru\PublicApi\Auth\LoginRequest:
    factory:
    - '@App\Factory\PublicApiFactory'
    - 'makePublicApiRequest'
    arguments:
    - '@request_stack'
    - '\Valkeru\PublicApi\Auth\LoginRequest'

  Valkeru\PublicApi\Auth\LogoutRequest:
    factory:
    - '@App\Factory\PublicApiFactory'
    - 'makePublicApiRequest'
    arguments:
    - '@request_stack'
    - '\Valkeru\PublicApi\Auth\LogoutRequest'

  Valkeru\PublicApi\Security\TokenInfoRequest:
    factory:
    - '@App\Factory\PublicApiFactory'
    - 'makePublicApiRequest'
    arguments:
    - '@request_stack'
    - '\Valkeru\PublicApi\Security\TokenInfoRequest'

  Valkeru\PublicApi\Security\BlacklistTokenRequest:
    factory:
    - '@App\Factory\PublicApiFactory'
    - 'makePublicApiRequest'
    arguments:
    - '@request_stack'
    - '\Valkeru\PublicApi\Security\BlacklistTokenRequest'

  Valkeru\PublicApi\Security\InvalidateAllTokensRequest:
    factory:
    - '@App\Factory\PublicApiFactory'
    - 'makePublicApiRequest'
    arguments:
    - '@request_stack'
    - '\Valkeru\PublicApi\Security\InvalidateAllTokensRequest'

  Valkeru\PublicApi\Security\ChangePasswordRequest:
    factory:
    - '@App\Factory\PublicApiFactory'
    - 'makePublicApiRequest'
    arguments:
    - '@request_stack'
    - '\Valkeru\PublicApi\Security\ChangePasswordRequest'

  Valkeru\PublicApi\Security\PublicKeyRequest:
    factory:
    - '@App\Factory\PublicApiFactory'
    - 'makePublicApiRequest'
    arguments:
    - '@request_stack'
    - '\Valkeru\PublicApi\Security\PublicKeyRequest'
